import { NextResponse } from 'next/server'
import NextAuth from 'next-auth'
import { authOptions } from '@/lib/auth'

const nextAuthHandler = NextAuth(authOptions)

/**
 * GET /api/auth/callback/google
 * Processes Google OAuth callback code exchange & session creation via NextAuth.
 * Preserves mobile authentication flow (redirecting to /auth/callback?is_mobile=true)
 * with session cookies attached.
 */
export async function GET(request: Request) {
  const urlObj = new URL(request.url)
  const state = urlObj.searchParams.get('state')

  let customCallbackUrl: string | null = null
  if (state) {
    try {
      const decoded = decodeURIComponent(state)
      if (decoded.includes('/auth/callback') || decoded.includes('is_mobile=true')) {
        customCallbackUrl = decoded
      }
    } catch {
      // ignore state parsing errors
    }
  }

  try {
    const nextAuthContext = { params: { nextauth: ['callback', 'google'] } }
    const response = await (nextAuthHandler as any)(request, nextAuthContext)

    if (customCallbackUrl && response) {
      console.log(
        '📱 [Google Callback Interceptor] NextAuth completed. Overriding redirect to:',
        customCallbackUrl
      )

      const redirectResponse = NextResponse.redirect(customCallbackUrl, {
        status: 302,
      })

      // Copy any Set-Cookie headers generated by NextAuth
      response.headers.forEach((value: string, key: string) => {
        if (key.toLowerCase() === 'set-cookie') {
          redirectResponse.headers.append('set-cookie', value)
        }
      })

      return redirectResponse
    }

    return response
  } catch (err) {
    console.error('❌ [Google Callback Interceptor] Error executing NextAuth handler:', err)
    return NextResponse.redirect(new URL('/sign-in?error=OAuthCallback', request.url))
  }
}

export async function POST(request: Request) {
  const nextAuthContext = { params: { nextauth: ['callback', 'google'] } }
  return (nextAuthHandler as any)(request, nextAuthContext)
}
